# Generated by Django 2.2 on 2019-04-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(help_text='Ingrese sus apellidos', max_length=100, verbose_name='Apellidos')),
                ('nombre', models.CharField(help_text='Ingrese su nombre', max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(help_text='Ingrese su correo electrónico', max_length=254)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(help_text='Ingrese el motivo de la consulta', max_length=50)),
                ('descripcion', models.TextField(help_text='Realice una breve descripción del motivo', max_length=200)),
            ],
            options={
                'verbose_name': 'Motivo de Consulta',
                'verbose_name_plural': 'Motivos',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='Ingrese su mensaje, no olvide detalles relevantes', max_length=500)),
                ('tema', models.ForeignKey(help_text='Seleccion un tema para su consulta', on_delete=django.db.models.deletion.CASCADE, to='novedades.Motivo')),
                ('usuario', models.ForeignKey(help_text='Datos del usuario', on_delete=django.db.models.deletion.CASCADE, to='novedades.Contacto')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
