# Generated by Django 2.2 on 2019-05-07 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='mensaje',
            field=models.TextField(help_text='Ingrese su mensaje, no olvide detalles relevantes', max_length=500, verbose_name='¿En qué podemos ayudarte?'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tema',
            field=models.ForeignKey(help_text='Seleccion un tema relacionado a su consulta', on_delete=django.db.models.deletion.CASCADE, to='novedades.Motivo', verbose_name='Tema de consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='usuario',
            field=models.ForeignKey(help_text='Datos del usuario', on_delete=django.db.models.deletion.CASCADE, to='novedades.Contacto', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(help_text='Ingrese su correo electrónico', max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(help_text='Ingrese su nombre', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='motivo',
            name='descripcion',
            field=models.TextField(help_text='Realice una breve descripción del motivo', max_length=200, verbose_name='Descripción del motivo'),
        ),
        migrations.AlterField(
            model_name='motivo',
            name='motivo',
            field=models.CharField(help_text='Ingrese el motivo de la consulta', max_length=50, verbose_name='Motivo de consulta'),
        ),
    ]
