# Generated by Django 2.2 on 2019-04-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Seleccione su fecha de nacimiento', null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
