# Generated by Django 2.2 on 2019-04-30 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_auto_20190430_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='Seleccione el país al que pertenece esta ciudad', null=True, on_delete=django.db.models.deletion.CASCADE, to='calculadora.Pais', verbose_name='País'),
        ),
    ]
