# Generated by Django 2.2 on 2019-04-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0004_auto_20190430_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre_ciudad',
            field=models.CharField(help_text='Ingrese el nombre de la ciudad', max_length=50, verbose_name='Nombre'),
        ),
    ]
