# Generated by Django 2.2 on 2019-04-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0006_auto_20190430_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='nombre_ciudad',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='continente',
            old_name='nombre_continente',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='idiomaoficial',
            old_name='nombre_idioma',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='nombre_pais',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='usuaio',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='tipocarta',
            old_name='decripcion',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='precio',
            name='producto',
            field=models.ForeignKey(default=None, help_text='Producto que se presenta una variación en su precio', on_delete=django.db.models.deletion.CASCADE, related_name='registra', to='calculadora.Producto', verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
