# Generated by Django 2.2 on 2019-04-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0007_auto_20190430_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='url',
            field=models.URLField(help_text='Dirección URL de la red social, en el formato: "https//www.redsocial.com"', max_length=100, verbose_name='Dirección URL'),
        ),
    ]
