# Generated by Django 2.2 on 2019-05-07 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0008_auto_20190430_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='continente',
            field=models.ForeignKey(blank=True, help_text='Contiente donde se ubica el país', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continente', to='calculadora.Continente', verbose_name='Continente'),
        ),
        migrations.AlterField(
            model_name='redsocial',
            name='url',
            field=models.URLField(help_text='Dirección URL de la red social, en el formato: "https://www.redsocial.com"', max_length=100, verbose_name='Dirección URL'),
        ),
    ]
