# Generated by Django 2.2 on 2019-05-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0009_auto_20190506_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['continente', 'nombre'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterField(
            model_name='pais',
            name='iso_3166_1_3',
            field=models.CharField(blank=True, help_text='Indique el código del país en formato ISO 3166-1 alpha-3. Por ejemplo, para la bandera de la República de El Salvador es SLV', max_length=3, null=True, verbose_name='Codigo ISO 3166-1 alpha-3'),
        ),
    ]
