# Generated by Django 2.2 on 2019-05-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0010_auto_20190506_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continente',
            name='nombre',
            field=models.CharField(help_text='Nombre del continente', max_length=20, verbose_name='Continente'),
        ),
    ]
