# Generated by Django 2.2 on 2019-05-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0011_auto_20190507_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continente',
            name='codigo',
            field=models.CharField(help_text='Codigo del continente', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='continente',
            name='nombre',
            field=models.CharField(help_text='Nombre del continente', max_length=25, verbose_name='Continente'),
        ),
    ]
