# Generated by Django 2.2 on 2019-05-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0012_auto_20190507_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del país', max_length=100, verbose_name='Nombre oficial'),
        ),
    ]
