# Generated by Django 2.2 on 2019-05-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0013_auto_20190507_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='iso_3166_1_2',
            field=models.CharField(blank=True, help_text='Indique el código del país en formato ISO 3166-1 alpha-2. Por ejemplo, para la bandera de la República de El Salvador es SV', max_length=3, null=True, verbose_name='Codigo ISO 3166-1 alpha-2'),
        ),
    ]
