# Generated by Django 2.2 on 2019-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0014_auto_20190507_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continente',
            options={'ordering': ['nombre'], 'verbose_name': 'Continente', 'verbose_name_plural': 'Continentes'},
        ),
        migrations.AlterField(
            model_name='idiomaoficial',
            name='nombre',
            field=models.CharField(help_text='Nombre del idioma', max_length=100, verbose_name='Idioma'),
        ),
    ]
