# Generated by Django 2.2 on 2019-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0015_auto_20190507_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idiomaoficial',
            options={'ordering': ['nombre'], 'verbose_name': 'Idioma Oficial', 'verbose_name_plural': 'Idiomas Oficiales'},
        ),
        migrations.AlterField(
            model_name='monedaoficial',
            name='iso_4217',
            field=models.CharField(help_text='Indique el código de la divisa en formato ISO 4217. Por ejemplo, para el peso argentino su codigo es "ARS"', max_length=3, unique=True, verbose_name='Codigo ISO 4217'),
        ),
    ]
