# Generated by Django 2.2 on 2019-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0016_auto_20190507_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monedaoficial',
            name='nombre_divisa',
            field=models.CharField(help_text='Indique el nombre de la moneda. Por ejemplo, la moneda de Argentina se llama "Peso argentino"', max_length=100, verbose_name='Moneda'),
        ),
    ]
