# Generated by Django 2.2 on 2019-05-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0017_auto_20190507_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monedaoficial',
            options={'ordering': ['nombre_divisa'], 'verbose_name': 'Moneda Oficial', 'verbose_name_plural': 'Monedas Oficiales'},
        ),
    ]
