# Generated by Django 2.2 on 2019-05-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0018_auto_20190509_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='mapa',
            field=models.CharField(blank=True, help_text='Si lo desea, puede generar el mapa de su ubicación en Google Maps. Vea el tutorial para más información', max_length=300, null=True, verbose_name='Mapa'),
        ),
    ]
