# Generated by Django 2.2 on 2019-05-13 01:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0019_restaurante_mapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='ciudad',
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre de la division', max_length=50, verbose_name='Nombre')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='La latitud está dada en grados decimales, entre 0° y 90 ° en el hemisferio Norte y entre 0° y -90° en el hemisferio Sur', max_digits=9, null=True, unique=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='La longitud está dada en grados decimales, entre 0° y 180°, al este del meridiano de Greenwich y entre 0° y -180°, al oeste del meridiano de Greenwich.', max_digits=9, null=True, unique=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitud')),
                ('ciudad', models.ForeignKey(blank=True, help_text='Seleccione la ciudad a la que pertenece esta region', null=True, on_delete=django.db.models.deletion.CASCADE, to='calculadora.Ciudad', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Diviión de la ciudad',
                'verbose_name_plural': 'Divisiones',
            },
        ),
        migrations.AddField(
            model_name='restaurante',
            name='barrio',
            field=models.ForeignKey(blank=True, help_text='Seleccione el barrio o división política de su ciudad en la que está ubicado el restaurante.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ubicado_en', to='calculadora.Division', verbose_name='Barrio/Division'),
        ),
    ]
