# Generated by Django 2.2 on 2019-05-13 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0020_auto_20190512_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'División política de la ciudad', 'verbose_name_plural': 'División Política'},
        ),
        migrations.AlterField(
            model_name='division',
            name='ciudad',
            field=models.ForeignKey(blank=True, help_text='Seleccione la ciudad a la que pertenece esta region', null=True, on_delete=django.db.models.deletion.CASCADE, to='calculadora.Ciudad', verbose_name='Ciudad'),
        ),
    ]
