# Generated by Django 2.2 on 2019-05-14 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0023_auto_20190513_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Ingrese una breve descripción de este producto (entre 50 y 300 caracteres)', max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Cargue una foto representativa de su producto', null=True, upload_to='Productos/', verbose_name='Foto del producto'),
        ),
    ]
