# Generated by Django 2.2 on 2019-05-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0024_auto_20190513_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='barrio',
            field=models.ForeignKey(blank=True, help_text='Seleccione el barrio o división política de su ciudad en la que está ubicado el restaurante.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ubicado_en', to='calculadora.Division', verbose_name='Barrio/Division'),
        ),
    ]
