# Generated by Django 2.2 on 2019-05-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0026_auto_20190520_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='restaurante',
            field=models.ForeignKey(help_text='Restaurante al que pertenece esta carta', on_delete=django.db.models.deletion.CASCADE, related_name='restaurante', to='calculadora.Restaurante', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='carta',
            field=models.ForeignKey(help_text='Seleccione la carta a la que corresponde su producto', on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='calculadora.Carta'),
        ),
    ]
