# Generated by Django 2.2 on 2019-05-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0027_auto_20190521_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='restaurante',
            field=models.ForeignKey(help_text='Restaurante al que pertenece esta carta', on_delete=django.db.models.deletion.CASCADE, related_name='seccion', to='calculadora.Restaurante', verbose_name='Restaurante'),
        ),
    ]
