# Generated by Django 2.2 on 2019-05-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0030_ciudad_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='foto',
            field=models.ImageField(blank=True, help_text='Cargue una imagen representativa de la ciudad', null=True, upload_to='ciudades', verbose_name='Fotografía de la ciudad'),
        ),
    ]
