# Generated by Django 2.2 on 2019-05-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0031_auto_20190521_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
    ]
