# Generated by Django 2.2 on 2019-05-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0032_auto_20190523_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='logo',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='background',
            field=models.ImageField(blank=True, help_text='Cargue una fotografía de su restaurante. Esta se usará como background', null=True, upload_to='restaurantes/', verbose_name='Fotografía'),
        ),
    ]
