# Generated by Django 2.2 on 2019-05-29 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0033_auto_20190527_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='ciudad',
            field=models.ForeignKey(help_text='Seleccione la ciudad a la que pertenece este restaurante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ubicado_en', to='calculadora.Ciudad', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='barrio',
            field=models.ForeignKey(help_text='Seleccione el barrio o división política de su ciudad en la que está ubicado el restaurante.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='se_localiza_en', to='calculadora.Division', verbose_name='Barrio/Division'),
        ),
    ]
