# Generated by Django 2.2 on 2019-06-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0034_auto_20190529_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carta',
            options={'ordering': ['restaurante', 'tipo'], 'verbose_name': 'Carta', 'verbose_name_plural': 'Cartas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['carta'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='restaurante',
            options={'ordering': ['nombre'], 'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.AlterModelOptions(
            name='tipocarta',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Carta', 'verbose_name_plural': 'Tipos de Carta'},
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='tipo_comida',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='comidas',
            field=models.ManyToManyField(help_text='Seleccione el/los tipos de comida servidos en este restaurante', related_name='comidas', to='calculadora.TipoComida', verbose_name='Tipo de comida'),
        ),
    ]
