# Generated by Django 2.2 on 2019-06-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0035_auto_20190602_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='comidas',
            field=models.ManyToManyField(help_text='Seleccione el/los tipos de comida servidos en este restaurante', to='calculadora.TipoComida', verbose_name='Tipo de comida'),
        ),
    ]
