# Generated by Django 2.2 on 2019-06-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0036_auto_20190602_0015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carta',
            unique_together={('tipo', 'restaurante')},
        ),
    ]
