# Generated by Django 2.2 on 2019-06-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0037_auto_20190602_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocial',
            name='clase_fa',
            field=models.CharField(help_text='Clase CSS de la red social para font-awesome. Ejemplo: facebook', max_length=15, null=True, verbose_name='Clase CSS'),
        ),
    ]
