# Generated by Django 2.2 on 2019-06-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0038_redsocial_clase_fa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precio',
            options={'ordering': ['-fecha_adicion'], 'verbose_name': 'Precio', 'verbose_name_plural': 'Precios'},
        ),
        migrations.AlterField(
            model_name='precio',
            name='moneda',
            field=models.ForeignKey(blank=True, help_text='Moneda en la que se ha registrado este precio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dado_en', to='calculadora.MonedaOficial', verbose_name='Moneda'),
        ),
    ]
