# Generated by Django 2.2 on 2019-06-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0039_auto_20190604_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restaurante',
            field=models.BooleanField(blank=True, default=False, help_text='Marca esta casilla si eres el administrador de un restaurante', null=True, verbose_name='¿Eres un restaurante?'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='url_perfil',
            field=models.URLField(help_text='Dirección URL de su perfil de la red social, en el formato similar a: "https://www.redsocial.com/miperfil"', max_length=100, verbose_name='Dirección URL del perfil'),
        ),
    ]
