# Generated by Django 2.2 on 2019-06-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0040_auto_20190606_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_restaurante',
            field=models.BooleanField(blank=True, default=False, help_text='Selecciona "Sí" si eres el administrador de un restaurante', null=True, verbose_name='¿Eres un restaurante?'),
        ),
    ]
