# Generated by Django 2.2 on 2019-06-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0042_auto_20190607_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocomida',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Ingrese una breve descripción de este tipo de comida', max_length=250, null=True, verbose_name='Descripción'),
        ),
    ]
