# Generated by Django 2.2 on 2019-06-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0043_auto_20190607_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['nombre', 'ciudad'], 'verbose_name': 'División política de la ciudad', 'verbose_name_plural': 'División Política'},
        ),
    ]
