# Generated by Django 2.2 on 2019-06-07 23:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0044_auto_20190607_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Ingrese el número telefónico del restaurante en el formato +999999999', max_length=128, null=True, region=None, unique=True, verbose_name='Número de Telefono'),
        ),
    ]
