# Generated by Django 2.2 on 2019-06-08 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0046_auto_20190608_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='restaurante',
            field=models.ForeignKey(default=1, help_text='Restaurante al que pertenece esta carta', on_delete=django.db.models.deletion.CASCADE, related_name='seccion', to='calculadora.Restaurante', verbose_name='Restaurante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='carta',
            field=models.ForeignKey(default=1, help_text='Seleccione la carta a la que corresponde su producto', on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='calculadora.Carta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='administrador',
            field=models.ForeignKey(default=1, help_text='Usuario que añadió este restaurante', on_delete=django.db.models.deletion.CASCADE, related_name='es_registrado_por', to=settings.AUTH_USER_MODEL, verbose_name='¿Quién lo registró?'),
            preserve_default=False,
        ),
    ]
