# Generated by Django 2.2 on 2019-06-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0050_auto_20190608_1732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carta',
            unique_together=set(),
        ),
    ]
